### ISSUE TITLE
  self = reduction.pickle.load(from_parent) EOFError: Ran out of input

### ISSUE THREAD

**Issue by manvirvirk** [conscienceli/IterNet#8]
hi, i m getting above mentioned error when running train.py file even when my hdf5 has been generated for training data. please help. Thanks

**Comment by conscienceli** [comment]
Hi! I think this may be caused by the dataset problem. Can you provide more information and the complete error message?

**Comment by manvirvirk** [comment]
@conscienceli  Thanks for the help. When i run prepare dataset.py file , it does not generate hdf5 file. I m using your pretrained model and my own test images. Thanks

**Comment by conscienceli** [comment]
well, okay, get it. I think I didn't write the code for conduct prediction on custom data. I think I can update a new version later. But you can also write it on your own.

**Comment by manvirvirk** [comment]
@conscienceli  even i cannot generate for DRIVE data as well. I tried with DRIVE also.

**Comment by manvirvirk** [comment]
whole traceback is:
 GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "predict.py", line 109, in <module>
    predict(batch_size=32, epochs=200, iteration=3, stride_size=3, DATASET='DRIVE')
  File "predict.py", line 27, in predict
    prepare_dataset.prepareDataset(DATASET)
  File "D:\IterNet-master\utils\prepare_dataset.py", line 121, in prepareDataset
    preprocessed = preprocessData(raw, dataset)
  File "D:\IterNet-master\utils\prepare_dataset.py", line 77, in preprocessData
    if data_path[0].find('mask') > 0:
IndexError: list index out of range

**Comment by conscienceli** [comment]
I think the problem is no files are found in the dataset path. Have you downloaded the drive dataset and put it in the required path?

**Comment by manvirvirk** [comment]
@conscienceli  Yes i have downloaded DRIVE dataset in the following path:
data-DRIVE-training-1st manual, images , mask
                    test-1st manual,2nd manual,images, mask

**Comment by manvirvirk** [comment]
Moreover no HDF5 is generated when i run prepare_dataset.py. without HDF5 file we cannot even predict our images by using pretrained model. Thanks for the help. @conscienceli

**Comment by conscienceli** [comment]
Another possible reason is that I didn't test this program on Windows platform. I think the "/" in the paths should be replaced by  \  on windows. Can you please try this? I am not very sure about this...

**Comment by manvirvirk** [comment]
@conscienceli Thanks for helping long way. May be this could be the reason as i m using windows 10 , GeForce RTX 20260. Let me try it and revert back.

**Comment by manvirvirk** [comment]
@conscienceli did not work for me. I created hdf5 file using another code, then it gets created. Does it needs any call function to create hdf5 file in prepare_dataset,py file?

**Comment by conscienceli** [comment]
addressed privately

**Comment by Chenguang-Wang** [comment]
I have the same problem. How did this problem get solved?
